### ISSUE TITLE
Collection adding error

### ISSUE THREAD

**Issue by pszemus** [esphen/RESTED#11] opened 2015-11-10 11:50 UTC
```
"An error occured when reading/writing to indexedDB: "{
  "success": false,
  "message": "An error occured when adding to database!",
  "object": {
    "isTrusted": true
  }
}
````
from firebug's console:
```
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.4.3/ngRepeat/dupes?p0=collection%20in%20collections%20%7C%20uuidAssign%3A'array'%20track%20by%20collection.id&p1=0eb0d189-8b16-e83e-d2db-4b4a4ee53ca8&p2=%7B%22name%22%3A%22live-encoder%22%2C%22requests%22%3A%5B%7B%22method%22%3A%22GET%22%2C%22headers%22%3A%5B%7B%22name%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%2C%22formData%22%3A%5B%7B%22name%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%2C%22cache%22%3Afalse%2C%22url%22%3A%22http%3A%2F%2Flive-encoder-1.ad.wp-sa.pl%3A8080%2Fstreaming%22%2C%22id%22%3A%222c1e25eb-aaa0-e842-8adf-78cd1b594b72%22%7D%2C%7B%22method%22%3A%22DELETE%22%2C%22headers%22%3A%5B%7B%22name%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%2C%22formData%22%3A%5B%7B%22name%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%2C%22cache%22%3Afalse%2C%22url%22%3A%22http%3A%2F%2Flive-encoder-1.ad.wp-sa.pl%3A8080%2Fstreaming%3FstreamName%3D1234%22%2C%22id%22%3A%223ea57d48-943b-066d-2e4f-b798c0c4dd52%22%7D%2C%7B%22method%22%3A%22PUT%22%2C%22headers%22%3A%5B%7B%22name%22%3A%22Content-Type%22%2C%22value%22%3A%22application%2Fvnd.wp.individual%2Bjson%22%7D%5D%2C%22formData%22%3A%5B%7B%22name%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%2C%22cache%22%3Afalse%2C%22url%22%3A%22http%3A%2F%2Flocalhost%3A8080%2Fwpencoder%2Fencodings%22%2C%22id%22%3A%223601cc22-4449-6df0-2768-a1e3d9809962%22%2C%22data%22%3A%22%7B%5Cn%20%20%20%5C%22inputFile%5C%22%3A%20%7B%5Cn%20%20%20%20%20%20%5C%22uri%5C%22%3A%20%5C%22ftp%3A%2F%2Fwptv-w%3ARHE6L2Guq8Lf%40ftp.wp.pl%2Fpszemus-big_buck_bunny_576p_stereo_30sek.avi%5C%22%5Cn%20%20%20%7D%2C%5Cn%20%20%20%5C%22outputFiles%5C%22%3A%20%5B%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%20%5C%22uri%5C%22%3A%20%5C%22h.webm%5C%22%2C%5Cn%20%20%20%20%20%20%20%20%20%5C%22type%5C%22%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%5C%22video%5C%22%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%22preset%5C%22%3A%20%5C%22WPTV_HQ_WEBM%5C%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%5D%2C%5Cn%20%20%20%5C%22storage%5C%22%3A%20%7B%5C%22proto%5C%22%3A%20%5C%22file%5C%22%7D%5Cn%7D%22%7D%5D%2C%22id%22%3A%220eb0d189-8b16-e83e-d2db-4b4a4ee53ca8%22%2C%22minimized%22%3Afalse%2C%22%24%24hashKey%22%3A%22object%3A80%22%7D
J/<@chrome://rested/content/ext/angular.min.js:6:416
De</<.compile/</<@chrome://rested/content/ext/angular.min.js:278:261
jf/this.$get</n.prototype.$watchCollection/<@chrome://rested/content/ext/angular.min.js:131:178
jf/this.$get</n.prototype.$digest@chrome://rested/content/ext/angular.min.js:132:257
jf/this.$get</n.prototype.$evalAsync/<@chrome://rested/content/ext/angular.min.js:135:76
e@chrome://rested/content/ext/angular.min.js:43:45
Jf/l.defer/c<@chrome://rested/content/ext/angular.min.js:45:442

chrome://rested/content/ext/angular.min.js
Line 108
```

Happened when I opened RESTED in two tabs and added some collections and requests to DB. Now all saved collections and requests are gone and I cannot create a new one.

**Comment by esphen** [comment] 2015-11-10 13:28
Shoot. Looks like you somehow managed to get two requests with the same id into the db. That breaks the repeater that lists the collections and requests. I'll see if I can reproduce and get a fix out for the next version. 

In the mean time, you probably need to run the following in the console to reset the DB and get the app working again: `indexedDB.deleteDatabase('RESTED');` Sorry for the inconvenience.

**Comment by theSoenke** [comment] 2016-04-02 11:36
Have the same issue

**Comment by esphen** [comment] 2016-09-23 22:29
RESTED is no longer using IndexedDB, so this should (hopefully) no longer happen. Closing this issue.

If you are able to export your collections before updating, please do so, as the upgrade to 1.0 will clear your saved data. This is because of the upgrade of the extension to the webextension API. After upgrading you can import your old data.

**Closed by esphen** 2016-09-23 22:29 UTC
Labels: bug
