### ISSUE TITLE
Allow sending insecure HTTPS requests

### ISSUE THREAD

**Issue by dror3go** [esphen/RESTED#65] opened 2016-10-27 15:53 UTC
Just like cURL on the command line enables the `-k` / `--insecure` flag, _RESTED_ should enable users to send insecure requests to HTTPS URLs.

My specific use case is of a staging 3rd party API that's enforces HTTPS for all requests, but that its certificate has expired.

Thanks

**Comment by esphen** [comment] 2016-10-27 16:15
I hear you. If you hang on until version 2.0 is released, your issue should be fixed.

The reason I say "hang on" is because as far as I can see, XHR (which is what RESTED uses to send requests) does not support sending insecure requests whatsoever. Searching for it results in weird suggestions like [proxying their connection through cURL with the insecure flag](https://stackoverflow.com/questions/20753793/xhr-bypass-expired-ssl-cert#20754294). You could look into using a curl proxy in the mean time, weird as it may be.

Version 2.0 will change from XHR to the fetch API. I just confirmed that setting a security execption in the browser enables `fetch` to do insecure requests like expired certificates.

2.0 is a long way off, however. Only basic sending of requests is implemented thus far. If you're desperate, you could [run RESTED from the `react-rewrite` branch](https://github.com/esphen/RESTED/tree/react-rewrite#how-to-contribute) and use that for your insecure requests.

Thanks for the suggestion.

**Closed** 2017-03-11 22:29 UTC
