### ISSUE TITLE
Adding new item after saving new Collection fails

### ISSUE THREAD

**Issue by cerkit** [esphen/RESTED#54] opened 2016-07-15 20:06 UTC
I received the following error after trying to create a new item immediately after creating a Collection (just after installing the addon):

    "An error occured when reading/writing to indexedDB: "{
      "success": false,
      "message": "An error occured when adding to database!",
      "object": {
        "isTrusted": true
      }
    }

**Comment by cerkit** [comment] 2016-07-15 20:19
It seems to happen when trying to add a new collection. Even though I get the error, the collection is created with the default name "Collection {number}". The collections show up after I refresh the page and I can rename them and they save correctly.

**Comment by esphen** [comment] 2016-07-19 14:43
Hi,

Are you able to consistently reproduce this issue? Or was it only after you installed the first time?

**Comment by esphen** [comment] 2016-09-23 22:09
RESTED is no longer using IndexedDB, so this should no longer happen. Closing this issue. Feel free to reopen if this happens again.

If you are able to export your collections before updating, please do so, as the upgrade to 1.0 will clear your saved data. This is because of the upgrade of the extension to the webextension API. After upgrading you can import your old data.

**Closed by esphen** 2016-09-23 22:09 UTC
